# Generated by Django 3.1.6 on 2021-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210307_0624'),
        ('store', '0003_auto_20210307_0449'),
    ]

    operations = [
    ]
