# Generated by Django 3.1.6 on 2021-03-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_20210307_1250'),
        ('store', '0004_auto_20210307_0653'),
        ('store', '0004_merge_20210307_1325'),
    ]

    operations = [
    ]
