# Generated by Django 3.1.6 on 2021-03-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_merge_20210311_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='FavouriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('meta_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.metaproduct')),
            ],
            options={
                'verbose_name': 'Favourite Product',
                'verbose_name_plural': 'Favourite Products',
            },
        ),
    ]
